### ISSUE TITLE
UI not aligned 

### ISSUE THREAD

**Issue by BM123499** [DeadMG/puppy-jetpack-ui#3]
![image](https://github.com/DeadMG/puppy-jetpack-ui/assets/48841672/ad64846a-aab1-4a29-8e39-9d6b9841034d)

I believe this is because my UI scale is 200%. Since I use a 4k screen to play the game, the default value for UI scaling is 200%, so it happens.

**Comment by DeadMG** [comment]
I'm also playing at 200%/4K. But this misalignment is a necessary sacrifice because I wanted the window to be draggable- you can use the drag handle on the left to position it where you want. This means I can't position it perfectly correctly to start.

In short, known tradeoff, just drag it where you want it.
